# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: alsi-lawr.ModConductor
PackageVersion: 0.1.1
InstallerType: nullsoft
Scope: user
InstallModes:
  - interactive
  - silent
InstallerSwitches:
  Silent: /S
  SilentWithProgress: /S
UpgradeBehavior: install
ProductCode: ModConductor
AppsAndFeaturesEntries:
  - ProductCode: ModConductor
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/ModConductor/ModConductor/releases/download/v0.1.1/ModConductor-0.1.1-win-x64-setup.exe
    InstallerSha256: 037D820D6385797FD6DD0C7E6ECFCA4FDE654A6372023903D6BEF54941060262
ManifestType: installer
ManifestVersion: 1.9.0
