# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: alsi-lawr.BlokeBot
PackageVersion: 0.16.0
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/alsi-lawr/BlokeBot/releases/download/v0.16.0/blokebot-v0.16.0-win-x64.zip
    InstallerSha256: 5e510098e51e21a60f48f523141e773f7b11b8d13127958b4e7e573ae0229511
    InstallerType: zip
    NestedInstallerType: portable
    ArchiveBinariesDependOnPath: true
    NestedInstallerFiles:
      - RelativeFilePath: blokebot-v0.16.0-win-x64\bin\blokebot.exe
        PortableCommandAlias: blokebot
  - Architecture: arm64
    InstallerUrl: https://github.com/alsi-lawr/BlokeBot/releases/download/v0.16.0/blokebot-v0.16.0-win-arm64.zip
    InstallerSha256: 8ae6be90a9f9205fbc0888eb2567706f10760da87cf486e6d7bbf87d3f7f6195
    InstallerType: zip
    NestedInstallerType: portable
    ArchiveBinariesDependOnPath: true
    NestedInstallerFiles:
      - RelativeFilePath: blokebot-v0.16.0-win-arm64\bin\blokebot.exe
        PortableCommandAlias: blokebot
ManifestType: installer
ManifestVersion: 1.9.0
