# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: alsi-lawr.BlokeBot
PackageVersion: 0.11.1
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/alsi-lawr/BlokeBot/releases/download/v0.11.1/blokebot-v0.11.1-win-x64.zip
    InstallerSha256: f73ba805f15681684f8b0c68c576ec77a331df2a8fa2fce4e77328bdfb6ab4a6
    InstallerType: zip
    NestedInstallerType: portable
    ArchiveBinariesDependOnPath: true
    NestedInstallerFiles:
      - RelativeFilePath: blokebot-v0.11.1-win-x64\bin\blokebot.exe
        PortableCommandAlias: blokebot
  - Architecture: arm64
    InstallerUrl: https://github.com/alsi-lawr/BlokeBot/releases/download/v0.11.1/blokebot-v0.11.1-win-arm64.zip
    InstallerSha256: fb38998886fe8309251309cbfc08cdbbaf9e383fd98a134328b25a32f6569397
    InstallerType: zip
    NestedInstallerType: portable
    ArchiveBinariesDependOnPath: true
    NestedInstallerFiles:
      - RelativeFilePath: blokebot-v0.11.1-win-arm64\bin\blokebot.exe
        PortableCommandAlias: blokebot
ManifestType: installer
ManifestVersion: 1.9.0
