# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: alsi-lawr.BlokeBot
PackageVersion: 0.14.0
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/alsi-lawr/BlokeBot/releases/download/v0.14.0/blokebot-v0.14.0-win-x64.zip
    InstallerSha256: 247db4189984fbf4c537a49ef6cbac5684dde43ee89339b6ddf1aeb14b10c093
    InstallerType: zip
    NestedInstallerType: portable
    ArchiveBinariesDependOnPath: true
    NestedInstallerFiles:
      - RelativeFilePath: blokebot-v0.14.0-win-x64\bin\blokebot.exe
        PortableCommandAlias: blokebot
  - Architecture: arm64
    InstallerUrl: https://github.com/alsi-lawr/BlokeBot/releases/download/v0.14.0/blokebot-v0.14.0-win-arm64.zip
    InstallerSha256: 0214dce8cbdc9298741298f016629efc0ae1d55696cc0babc555a76f6f25eec1
    InstallerType: zip
    NestedInstallerType: portable
    ArchiveBinariesDependOnPath: true
    NestedInstallerFiles:
      - RelativeFilePath: blokebot-v0.14.0-win-arm64\bin\blokebot.exe
        PortableCommandAlias: blokebot
ManifestType: installer
ManifestVersion: 1.9.0
