# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: alsi-lawr.BlokeBot
PackageVersion: 0.11.2
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/alsi-lawr/BlokeBot/releases/download/v0.11.2/blokebot-v0.11.2-win-x64.zip
    InstallerSha256: 04c47973b6f1db5a41329a2c04cc2b9ebb4a42662b54b8de85b36db8730f8d2a
    InstallerType: zip
    NestedInstallerType: portable
    ArchiveBinariesDependOnPath: true
    NestedInstallerFiles:
      - RelativeFilePath: blokebot-v0.11.2-win-x64\bin\blokebot.exe
        PortableCommandAlias: blokebot
  - Architecture: arm64
    InstallerUrl: https://github.com/alsi-lawr/BlokeBot/releases/download/v0.11.2/blokebot-v0.11.2-win-arm64.zip
    InstallerSha256: 99938c23331a1554e205a5a1be7e736a29112ac59c129e198100f7e7dc61f956
    InstallerType: zip
    NestedInstallerType: portable
    ArchiveBinariesDependOnPath: true
    NestedInstallerFiles:
      - RelativeFilePath: blokebot-v0.11.2-win-arm64\bin\blokebot.exe
        PortableCommandAlias: blokebot
ManifestType: installer
ManifestVersion: 1.9.0
