# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: alsi-lawr.BlokeBot
PackageVersion: 0.7.2
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/alsi-lawr/BlokeBot/releases/download/v0.7.2/blokebot-v0.7.2-win-x64.zip
    InstallerSha256: e7f22e12147ae69f55fb994e7a9dfb76b376d43a137a4f3cd89030436e293061
    InstallerType: zip
    NestedInstallerType: portable
    ArchiveBinariesDependOnPath: true
    NestedInstallerFiles:
      - RelativeFilePath: blokebot-v0.7.2-win-x64\bin\blokebot.exe
        PortableCommandAlias: blokebot
  - Architecture: arm64
    InstallerUrl: https://github.com/alsi-lawr/BlokeBot/releases/download/v0.7.2/blokebot-v0.7.2-win-arm64.zip
    InstallerSha256: b95ba415bab333c75a9d37494c5f5496b4387933f16bc614c8baee901a2c18d1
    InstallerType: zip
    NestedInstallerType: portable
    ArchiveBinariesDependOnPath: true
    NestedInstallerFiles:
      - RelativeFilePath: blokebot-v0.7.2-win-arm64\bin\blokebot.exe
        PortableCommandAlias: blokebot
ManifestType: installer
ManifestVersion: 1.9.0
